# PR Labeler Configuration
# Automatically labels PRs based on changed files
# https://github.com/actions/labeler

# Core domain logic
core:
  - changed-files:
      - any-glob-to-any-file: "src/spectryn/core/**/*"

# Adapters layer
adapters:
  - changed-files:
      - any-glob-to-any-file: "src/spectryn/adapters/**/*"

# CLI changes
cli:
  - changed-files:
      - any-glob-to-any-file: "src/spectryn/cli/**/*"

# Application layer
application:
  - changed-files:
      - any-glob-to-any-file: "src/spectryn/application/**/*"

# Plugin system
plugins:
  - changed-files:
      - any-glob-to-any-file:
          - "src/spectryn/plugins/**/*"
          - "tests/plugins/**/*"

# Documentation changes
documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**/*"
          - "**/*.md"
          - "!CHANGELOG.md"

# Test changes
tests:
  - changed-files:
      - any-glob-to-any-file: "tests/**/*"

# CI/CD changes
ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**/*"
          - "Makefile"
          - "Dockerfile"
          - ".dockerignore"

# Configuration changes
config:
  - changed-files:
      - any-glob-to-any-file:
          - "pyproject.toml"
          - "setup.cfg"
          - ".pre-commit-config.yaml"
          - ".editorconfig"
          - ".env.example"

# Integrations (VS Code, Neovim, Terraform, GitHub Action)
integrations:
  - changed-files:
      - any-glob-to-any-file: "integrations/**/*"

# VS Code extension specifically
vscode:
  - changed-files:
      - any-glob-to-any-file: "integrations/vscode/**/*"

# GitHub Action integration
github-action:
  - changed-files:
      - any-glob-to-any-file: "integrations/github-action/**/*"

# Security-related changes
security:
  - changed-files:
      - any-glob-to-any-file:
          - "SECURITY.md"
          - "**/security/**/*"
          - ".github/dependabot.yml"

# Size labels based on lines changed (requires size plugin)
# These are handled by the labeler workflow with custom logic
