# Example workflow for pulling from Jira to markdown
# This creates a PR with updated documentation

name: Pull from Jira

on:
  # Weekly sync from Jira
  schedule:
    - cron: '0 9 * * 1'  # Every Monday at 9 AM UTC
  
  # Manual trigger
  workflow_dispatch:

jobs:
  pull:
    runs-on: ubuntu-latest
    name: Pull from Jira
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Pull from Jira
        id: pull
        uses: spectryn/spectryn-action@v1
        with:
          markdown-file: docs/EPIC.md
          epic-key: PROJ-123
          jira-url: ${{ secrets.JIRA_URL }}
          jira-email: ${{ secrets.JIRA_EMAIL }}
          jira-api-token: ${{ secrets.JIRA_API_TOKEN }}
          pull: true
          pull-output: docs/EPIC.md
      
      - name: Check for changes
        id: changes
        run: |
          git diff --quiet docs/EPIC.md && echo "changed=false" >> $GITHUB_OUTPUT || echo "changed=true" >> $GITHUB_OUTPUT
      
      - name: Create Pull Request
        if: steps.changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'docs: sync from Jira'
          title: '📋 Update documentation from Jira'
          body: |
            This PR updates the documentation to match the current state in Jira.
            
            ## Changes
            - Updated stories and descriptions
            - Updated subtask status
            - Synced acceptance criteria
            
            ---
            _Auto-generated by spectryn GitHub Action_
          branch: jira-sync/update-docs
          delete-branch: true
          labels: |
            documentation
            automated

