"""
Shell Completions - Generate shell completion scripts for md2jira.

Supports Bash, Zsh, and Fish shells.
"""

from pathlib import Path
from typing import Optional


# Embedded completion scripts (for dynamic generation)
BASH_COMPLETION = '''#!/bin/bash
# Bash completion script for md2jira
# Generated by: md2jira --completions bash

_md2jira_completions() {
    local cur prev opts
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    
    # All available options
    opts="--markdown -m --epic -e --execute -x --no-confirm --phase --story --config -c --jira-url --project --verbose -v --no-color --export --validate --interactive -i --version --help -h --completions"
    
    # Phase choices
    phases="all descriptions subtasks comments statuses"
    
    # Handle option-specific completions
    case "${prev}" in
        --markdown|-m)
            COMPREPLY=( $(compgen -f -X '!*.md' -- "${cur}") )
            COMPREPLY+=( $(compgen -d -- "${cur}") )
            return 0
            ;;
        --config|-c)
            COMPREPLY=( $(compgen -f -X '!*.yaml' -- "${cur}") )
            COMPREPLY+=( $(compgen -f -X '!*.yml' -- "${cur}") )
            COMPREPLY+=( $(compgen -f -X '!*.toml' -- "${cur}") )
            COMPREPLY+=( $(compgen -d -- "${cur}") )
            return 0
            ;;
        --export)
            COMPREPLY=( $(compgen -f -X '!*.json' -- "${cur}") )
            COMPREPLY+=( $(compgen -d -- "${cur}") )
            return 0
            ;;
        --phase)
            COMPREPLY=( $(compgen -W "${phases}" -- "${cur}") )
            return 0
            ;;
        --completions)
            COMPREPLY=( $(compgen -W "bash zsh fish" -- "${cur}") )
            return 0
            ;;
        --epic|-e|--story|--jira-url|--project)
            return 0
            ;;
    esac
    
    if [[ "${cur}" == -* ]]; then
        COMPREPLY=( $(compgen -W "${opts}" -- "${cur}") )
        return 0
    fi
    
    COMPREPLY=( $(compgen -f -- "${cur}") )
}

complete -F _md2jira_completions md2jira
'''

ZSH_COMPLETION = '''#compdef md2jira
# Zsh completion script for md2jira
# Generated by: md2jira --completions zsh

_md2jira() {
    local curcontext="$curcontext" state line
    typeset -A opt_args
    
    local -a phases
    phases=(
        'all:Run all sync phases'
        'descriptions:Sync story descriptions only'
        'subtasks:Sync subtasks only'
        'comments:Sync comments only'
        'statuses:Sync statuses only'
    )
    
    local -a shells
    shells=(
        'bash:Generate Bash completion script'
        'zsh:Generate Zsh completion script'
        'fish:Generate Fish completion script'
    )
    
    _arguments -C \\
        '(-m --markdown)'{-m,--markdown}'[Path to markdown epic file]:markdown file:_files -g "*.md"' \\
        '(-e --epic)'{-e,--epic}'[Jira epic key (e.g., PROJ-123)]:epic key:' \\
        '(-x --execute)'{-x,--execute}'[Execute changes (default is dry-run)]' \\
        '--no-confirm[Skip confirmation prompts]' \\
        '--phase[Which phase to run]:phase:->phases' \\
        '--story[Filter to specific story ID]:story id:' \\
        '(-c --config)'{-c,--config}'[Path to config file]:config file:_files -g "*.{yaml,yml,toml}"' \\
        '--jira-url[Override Jira URL]:url:_urls' \\
        '--project[Override Jira project key]:project key:' \\
        '(-v --verbose)'{-v,--verbose}'[Verbose output]' \\
        '--no-color[Disable colored output]' \\
        '--export[Export analysis to JSON file]:json file:_files -g "*.json"' \\
        '--validate[Validate markdown file format]' \\
        '(-i --interactive)'{-i,--interactive}'[Interactive mode with step-by-step guided sync]' \\
        '--version[Show version and exit]' \\
        '--completions[Generate shell completion script]:shell:->shells' \\
        '(-h --help)'{-h,--help}'[Show help message]' \\
        '*:markdown file:_files -g "*.md"'
    
    case "$state" in
        phases)
            _describe -t phases 'sync phase' phases
            ;;
        shells)
            _describe -t shells 'shell type' shells
            ;;
    esac
}

_md2jira "$@"
'''

FISH_COMPLETION = '''# Fish completion script for md2jira
# Generated by: md2jira --completions fish

complete -c md2jira -f

# Required arguments
complete -c md2jira -s m -l markdown -d 'Path to markdown epic file' -r -F -a '*.md'
complete -c md2jira -s e -l epic -d 'Jira epic key (e.g., PROJ-123)' -x

# Execution mode
complete -c md2jira -s x -l execute -d 'Execute changes (default is dry-run)'
complete -c md2jira -l no-confirm -d 'Skip confirmation prompts'

# Phase control
complete -c md2jira -l phase -d 'Which phase to run' -x -a '
    all\\t"Run all sync phases"
    descriptions\\t"Sync story descriptions only"
    subtasks\\t"Sync subtasks only"
    comments\\t"Sync comments only"
    statuses\\t"Sync statuses only"
'

# Filters
complete -c md2jira -l story -d 'Filter to specific story ID (e.g., US-001)' -x

# Configuration
complete -c md2jira -s c -l config -d 'Path to config file' -r -F -a '*.yaml *.yml *.toml'
complete -c md2jira -l jira-url -d 'Override Jira URL' -x
complete -c md2jira -l project -d 'Override Jira project key' -x

# Output options
complete -c md2jira -s v -l verbose -d 'Verbose output'
complete -c md2jira -l no-color -d 'Disable colored output'
complete -c md2jira -l export -d 'Export analysis to JSON file' -r -F -a '*.json'

# Special modes
complete -c md2jira -l validate -d 'Validate markdown file format'
complete -c md2jira -s i -l interactive -d 'Interactive mode with step-by-step guided sync'
complete -c md2jira -l version -d 'Show version and exit'
complete -c md2jira -s h -l help -d 'Show help message'

# Shell completions
complete -c md2jira -l completions -d 'Generate shell completion script' -x -a '
    bash\\t"Generate Bash completion script"
    zsh\\t"Generate Zsh completion script"  
    fish\\t"Generate Fish completion script"
'
'''


def get_completion_script(shell: str) -> Optional[str]:
    """
    Get the completion script for a specific shell.
    
    Args:
        shell: Shell type ('bash', 'zsh', or 'fish').
        
    Returns:
        The completion script as a string, or None if shell is not supported.
    """
    scripts = {
        'bash': BASH_COMPLETION,
        'zsh': ZSH_COMPLETION,
        'fish': FISH_COMPLETION,
    }
    return scripts.get(shell.lower())


def get_installation_instructions(shell: str) -> str:
    """
    Get installation instructions for a specific shell.
    
    Args:
        shell: Shell type ('bash', 'zsh', or 'fish').
        
    Returns:
        Installation instructions as a string.
    """
    shell = shell.lower()
    
    if shell == 'bash':
        return """
# Bash Completion Installation

Option 1: Add to ~/.bashrc
  echo 'eval "$(md2jira --completions bash)"' >> ~/.bashrc
  source ~/.bashrc

Option 2: Save to file and source
  md2jira --completions bash > ~/.local/share/bash-completion/completions/md2jira
  
Option 3: System-wide (requires sudo)
  sudo md2jira --completions bash > /etc/bash_completion.d/md2jira
"""

    elif shell == 'zsh':
        return """
# Zsh Completion Installation

Option 1: Add to ~/.zshrc
  echo 'eval "$(md2jira --completions zsh)"' >> ~/.zshrc
  source ~/.zshrc

Option 2: Save to completions directory
  mkdir -p ~/.zsh/completions
  md2jira --completions zsh > ~/.zsh/completions/_md2jira
  # Add to ~/.zshrc: fpath=(~/.zsh/completions $fpath)
  # Then run: autoload -Uz compinit && compinit
"""

    elif shell == 'fish':
        return """
# Fish Completion Installation

Option 1: Add to config.fish
  echo 'md2jira --completions fish | source' >> ~/.config/fish/config.fish

Option 2: Save to completions directory
  md2jira --completions fish > ~/.config/fish/completions/md2jira.fish
"""

    return f"Unknown shell: {shell}. Supported shells: bash, zsh, fish"


def print_completion(shell: str) -> bool:
    """
    Print the completion script for a specific shell.
    
    Args:
        shell: Shell type ('bash', 'zsh', or 'fish').
        
    Returns:
        True if script was printed, False if shell is not supported.
    """
    script = get_completion_script(shell)
    if script:
        print(script)
        return True
    
    print(f"Error: Unknown shell '{shell}'. Supported shells: bash, zsh, fish")
    return False


SUPPORTED_SHELLS = ['bash', 'zsh', 'fish']

