{{/*
Copyright (c) spectra
SPDX-License-Identifier: MIT
*/}}

{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "spectra.fullname" . }}-manager
  labels:
    {{- include "spectra.labels" . | nindent 4 }}
rules:
  # SpectraSync resources
  - apiGroups:
      - spectra.io
    resources:
      - spectrasyncs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - spectra.io
    resources:
      - spectrasyncs/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - spectra.io
    resources:
      - spectrasyncs/finalizers
    verbs:
      - update
  # Jobs
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  # Core resources
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "spectra.fullname" . }}-manager
  labels:
    {{- include "spectra.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "spectra.fullname" . }}-manager
subjects:
  - kind: ServiceAccount
    name: {{ include "spectra.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
{{- if .Values.operator.leaderElection.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "spectra.fullname" . }}-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spectra.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "spectra.fullname" . }}-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spectra.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "spectra.fullname" . }}-leader-election
subjects:
  - kind: ServiceAccount
    name: {{ include "spectra.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
