{{/*
Copyright (c) spectryn
SPDX-License-Identifier: MIT
*/}}

{{- if and .Values.operator.enabled .Values.operator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spectryn.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spectryn.labels" . | nindent 4 }}
  {{- with .Values.operator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
